import { createAccessControl } from "better-auth/plugins/access";
import { PERMISSION_RESOURCES, PERMISSION_ACTIONS } from "./constants";

export const statement = {
    [PERMISSION_RESOURCES.PROJECT]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.SHARE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.ORGANIZATION]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.USER]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.BAN,
        PERMISSION_ACTIONS.UNBAN,
        PERMISSION_ACTIONS.SET_ROLE,
        PERMISSION_ACTIONS.SET_PASSWORD,
        PERMISSION_ACTIONS.IMPERSONATE,
        PERMISSION_ACTIONS.GET,
    ],
    [PERMISSION_RESOURCES.API_KEY]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.ROLE]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.TEAM]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.INVITE,
        PERMISSION_ACTIONS.REMOVE,
    ],
    [PERMISSION_RESOURCES.MEMBER]: [
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.INVITATION]: [
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.CANCEL,
    ],
    [PERMISSION_RESOURCES.FILE]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.UPLOAD,
        PERMISSION_ACTIONS.DOWNLOAD,
    ],
    [PERMISSION_RESOURCES.SETTINGS]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.SESSION]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.REVOKE,
    ],
} as const;

export const accessControl = createAccessControl(statement);

export const memberRole = accessControl.newRole({ 
    [PERMISSION_RESOURCES.PROJECT]: [PERMISSION_ACTIONS.CREATE], 
}); 

export const adminRole = accessControl.newRole({
    [PERMISSION_RESOURCES.PROJECT]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.SHARE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.ORGANIZATION]: [
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.USER]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.BAN,
        PERMISSION_ACTIONS.UNBAN,
        PERMISSION_ACTIONS.SET_ROLE,
        PERMISSION_ACTIONS.SET_PASSWORD,
        PERMISSION_ACTIONS.IMPERSONATE,
        PERMISSION_ACTIONS.GET,
    ],
    [PERMISSION_RESOURCES.API_KEY]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.ROLE]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.TEAM]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.INVITE,
        PERMISSION_ACTIONS.REMOVE,
    ],
    [PERMISSION_RESOURCES.FILE]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.UPLOAD,
        PERMISSION_ACTIONS.DOWNLOAD,
    ],
    [PERMISSION_RESOURCES.SETTINGS]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.SESSION]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.REVOKE,
    ],
}); 

export const ownerRole = accessControl.newRole({ 
    [PERMISSION_RESOURCES.PROJECT]: [
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.ROLE]: [PERMISSION_ACTIONS.READ],
    [PERMISSION_RESOURCES.TEAM]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.INVITE,
        PERMISSION_ACTIONS.REMOVE,
    ],
}); 

export const myCustomRole = accessControl.newRole({ 
    [PERMISSION_RESOURCES.PROJECT]: [
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ], 
    [PERMISSION_RESOURCES.ORGANIZATION]: [PERMISSION_ACTIONS.UPDATE], 
});

export const moderatorRole = accessControl.newRole({
    [PERMISSION_RESOURCES.PROJECT]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
    ],
    [PERMISSION_RESOURCES.ORGANIZATION]: [
        PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.USER]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.TEAM]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.REMOVE,
    ],
    [PERMISSION_RESOURCES.FILE]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.DELETE,
        PERMISSION_ACTIONS.DOWNLOAD,
    ],
    [PERMISSION_RESOURCES.SETTINGS]: [PERMISSION_ACTIONS.READ],
});

export const editorRole = accessControl.newRole({
    [PERMISSION_RESOURCES.PROJECT]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.SHARE,
        PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.ORGANIZATION]: [
        PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.TEAM]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.INVITE,
    ],
    [PERMISSION_RESOURCES.FILE]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.CREATE,
        PERMISSION_ACTIONS.UPDATE,
        PERMISSION_ACTIONS.UPLOAD,
        PERMISSION_ACTIONS.DOWNLOAD,
    ],
    [PERMISSION_RESOURCES.SETTINGS]: [PERMISSION_ACTIONS.READ],
});

export const viewerRole = accessControl.newRole({
    [PERMISSION_RESOURCES.PROJECT]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.USER]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.TEAM]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.FILE]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.DOWNLOAD,
    ],
    [PERMISSION_RESOURCES.SETTINGS]: [PERMISSION_ACTIONS.READ],
});

export const supportRole = accessControl.newRole({
    [PERMISSION_RESOURCES.USER]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.ORGANIZATION]: [
        PERMISSION_ACTIONS.UPDATE,
    ],
    [PERMISSION_RESOURCES.TEAM]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.LIST,
        PERMISSION_ACTIONS.VIEW,
    ],
    [PERMISSION_RESOURCES.SETTINGS]: [
        PERMISSION_ACTIONS.READ,
        PERMISSION_ACTIONS.UPDATE,
    ],
}); 